use core::str::FromStr;
use alloc::string::String;
use crate::circuit_builder::{Address, Area, Range};

grammar;

// NOTE: Some descriptions are simplified.

Letter: u8 = <c:r"[a-zA-Z]"> => c.as_bytes()[0].to_ascii_uppercase() - b'A' + 1;

A1RelativeColum: u32 = {
    <n1: Letter> => n1 as u32 - 1,
    <n1: Letter> <n2: Letter> => n1 as u32 * 26 + n2 as u32 - 1,
} 

A1Column: u32 = {
    A1RelativeColum,
    "$" <A1RelativeColum>
}

RowDigitSequence: u32 = <s:r"[1-9][0-9]{0,4}"> => u32::from_str(s).unwrap();

A1RelativeRow: u32 = RowDigitSequence;

// Simplified char.
// https://www.w3.org/TR/2008/REC-xml-20081126/#charsets
Char: String = <"[a-zA-Z0-1]*"> => String::from(<>);

A1Row: u32 = {
    A1RelativeRow,
    "$" <A1RelativeRow>
}

pub A1Cell: Address = <A1Column> <A1Row> => Address::new(<>);

pub A1Area: Area = <A1Cell> ":" <A1Cell> => Area::new(<>);

A1Reference: Area = A1Area;

ExternalCellReference: Range = SingleSheetReference;

SingleSheetReference: Range = <SingleSheetPrefix> <A1Reference> => Range::new(<>);

SingleSheetPrefix: String = <SingleSheet> "!";

SingleSheet: String = SheetName;

SheetName: String = SheetNameCharacters;

SheetNameCharacters: String = Char;

pub CellReference: Range = ExternalCellReference;
