[package]
name = "lileum-commit"
version = "0.1.0"
edition = "2024"
description = "Commitment scheme traits and implementations for Lileum"
repository = "https://github.com/LileumLabs/lileum"
license = "MIT OR Apache-2.0"

[dependencies]
ark-ff = "0.4"
ark-serialize = { version = "0.4", default-features = false, features = ["derive"] }
ark-ec = { version = "0.4", optional = true }
rand = {version = "0.8", default-features = false, features = ["std_rng"], optional = true}
sumcheck = { workspace = true }
sumcheck-derive = { workspace = true }
reduction = { workspace = true }
sponge = { workspace = true }
hash-to-curve = { workspace = true, optional = true }

[dev-dependencies]
ark-vesta = "0.4"

[features]
ipa = ["dep:ark-ec", "dep:hash-to-curve", "dep:rand"]

[lib]
bench = false
