[package]
name = "lileum-sumcheck-derive"
version = "0.1.0"
edition = "2024"
description = "Derive macro for lileum-sumcheck"
repository = "https://github.com/LileumLabs/lileum"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"

